### PR TITLE
Fix changeRoles by updating remaining columns

### LINKED ISSUE #2: Role change fails / updatedAt does not have default value
Login as Admin > User list > Click on an existing user.
At the bottom of the form (Roles section), select an unselected radio button (e.g. Guard). Click "Save Role Assignments." Request hangs (stacktrace produced) and the role is not changed in the DB.

### PR DESCRIPTION
**Pull request by enerve**
This is a small change but I appreciate all feedback. This is also my first ever pull-request on github.

Fixes #2

### CODE REVIEW

**Comment by kbsymanz** [comment]
@enerve: Thanks for the pull request. I'll review it in the next day or so and get back with you. One question, are you able to reliably reproduce the steps to produce the error that this PR is addressing?

**Comment by enerve** [comment]
Yes I can repro it reliably.
Login as Admin > User list > Click on an existing user.
At the bottom of the form (Roles section), select an unselected radio button (e.g. Guard). Click "Save Role Assignments." Request hangs (stacktrace produced) and the role is not changed in the DB.

With this fix, the role changes in the DB, and screen returns to user list.

**Comment by kbsymanz** [comment]
@enerve: Thanks for the steps. Those are what I would have guessed and have tried but I cannot reproduce the issue so it has me wondering why. Let me look into it a bit more ...

**Comment by enerve** [comment]
Does your user_role table have "updatedAt" defined as NOT NULL? That's what's causing my error.

https://github.com/kbsymanz/midwife-EMR/blob/master/database/sql/create_tables.sql#L52

**Comment by kbsymanz** [comment]
@enerve, yes mine has the NOT NULL constraint on the updatedAt column in user_role but I am not encountering the issue. Line 108 of models/DB.js should take care of any missing updatedAt fields during the process of the save.

**Comment by enerve** [comment]
Interesting. 
I did some testing and it looks like "saving()" is not called for changes to user_role table. I'm guessing this is because user_role is not defined as a model / does not extend Bookshelf.DB.Model. 
Maybe the answer to this issue is to define it as a model and use "relation.through()" to use UserRole as a pivot table between User and Role.

Is it possible you have an older version of Bookshelf library?

**Comment by kbsymanz** [comment]
@enerve: In development I am using Bookshelf 0.7.9 which is current. I see your point about user_role not being defined as a model and thus not extending Bookshelf.DB.Model where the saving() method is defined. Yet that does not explain why I am not getting the failure in my installation nor why the clinic, which is actively piloting the software, is not getting this issue either. I will look into this further.

**Comment by kbsymanz** [comment]
@enerve: I manually merged your PR. Thanks.

**Pull request closed without merging**
